# Generated by Django 4.2.9 on 2024-02-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="image",
            field=models.ImageField(blank=True, upload_to="uploads/product/"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
