# Generated by Django 5.0.2 on 2024-02-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount_available', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='uploads/product/')),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='image',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='price',
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('f', 'Fulfilled')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pharmacyinventory'),
        ),
    ]
