# Generated by Django 5.0.2 on 2024-02-19 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_patient_user_remove_physician_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('u', 'Unconfirmed'), ('c', 'Confirmed'), ('r', 'Cancelled'), ('a', 'Attended')], default='u', help_text='Whether the appointment has been confirmed or not', max_length=1),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
